config/routes.rb
Proj::Application.routes.draw do
  get "welcome/index"
  resources :quotes
  resources :follows
  resources :likes
  root 'welcome#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  
get '/signup' => 'users#new'
post '/users' => 'users#create'

  

end

app/models/follow.rb
class Follow < ActiveRecord::Base
end

app/models/quotes.rb
class Quotes < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  
  def authorize
      redirect_to '/login' unless current_user
  end
  
  def show_time(q)
      if (q.created_at - (4*60*60)).hour == 0
          isPM = false
          timeShow = "12:"
        elsif (q.created_at - (4*60*60)).hour > 12
          timeShow = (((q.created_at - (4*60*60)).hour) - 12).to_s + ":"
        elsif (q.created_at - (4*60*60)).hour == 12
          timeShow = "12:"
          isPM = true
        else
          timeShow = ((q.created_at - (4*60*60)).hour).to_s + ":"
          isPM = false
      end
      
      
      
      if (q.created_at - (4*60*60)).min < 10
          timeShow = timeShow + "0"
      end
      timeShow = timeShow + (q.created_at - (4*60*60)).min.to_s
      
      
      
      if isPM == false
          timeShow = timeShow + " AM"
      else
          timeShow = timeShow + " PM"
      end
  end
  helper_method :show_time
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
    def new
        @currentUser ||= User.find(session[:user_id]).name if session[:user_id]
    end
    def show
        @follow = Follow.find(params[:id])
    end
    def create
        @follow = Follow.new(follow_params)
        @follow.save
        redirect_to @follow
    end
    private
    def follow_params
        params.require(:follows).permit(:follower, :following)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def new
        followingg = Follow.where(:follower => current_user.name)
        followingname = []
        followingg.each do |f|
            followingname.push(f.following)
        end
        @thequotes = Quotes.where(:user => followingname).order('created_at DESC')
        
    end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
    def index
        @quotess = Quotes.all
    end
    def show
        @quote = Quotes.find(params[:id])
    end
    def new
        @currentUser ||= User.find(session[:user_id]).name if session[:user_id]
    end
    def create
        @quote = Quotes.new(quote_params)
        @quote.save
        redirect_to @quote
    end
    private
    def quote_params
        params.require(:quotes).permit(:words, :author, :user)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

   def create
    user = User.find_by_name(params[:name])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user 
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
    end

    def create
    	user = User.new(user_params)
    	if user.save
     	 session[:user_id] = user.id
      	 redirect_to '/'
    	else
      	 redirect_to '/signup'
    	end
    end 

    def user_params
    	params.require(:user).permit(:name, :password, :password_confirmation)
  	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
before_filter :authorize
  def index
    @quotess = Quotes.where(:user => current_user.name).order('created_at DESC')
    @followercount = Follow.where(:following => current_user.name).count
    @followingcount = Follow.where(:follower => current_user.name).count

  end
  
  def destroy
      @quotess = Quotes.find(params[:id])
      @quotess.destroy
      
      redirect_to welcome_index_path
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/follow_helper.rb
module FollowHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/follows/new.html.erb
<%= form_for :follows, url: follows_path do |f| %>  
 	<%= f.hidden_field :follower, :value => @currentUser.to_s %>

<p>
    <%= f.label :Username %><br>
    <%= f.text_field :following %>
  </p>

  <p>
    <%= f.submit %>
  </p>
  <%= link_to(image_tag("back2.png"), welcome_index_path) %>

<% end %>

app/views/follows/show.html.erb
<h1 style="color:blue;font-size:35px" >Confirmed!</h1>
<p style="color:blue;font-size:30px">
  You just followed, <%= @follow.following %>
</p>
 
<%= link_to(image_tag("back2.png"), welcome_index_path) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Proj</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
  <p style="color:blue">Welcome <%= current_user.name %> | <%= link_to "Logout", '/logout' %></p>
<% else %>
  <%= link_to(image_tag("login.png"), '/login') %>
  <%= link_to(image_tag("signup.png"), '/signup') %>

<% end %>

<%= yield %>

</body>
</html>

app/views/likes/new.html.erb
<% @thequotes.each do |q| %>
	<div id="quote_show">
		<div id="timee"> 
			<%= q.user %> <br>
			<%= (q.created_at - (4*60*60)).month %> / <%= (q.created_at - (4*60*60)).day %> <br>
			<%= show_time(q) %>
		</div>
    	 "<%= q.words %>" <br>
   		  - <%= q.author %> <br>
    </div>
    
  <% end %>
    <%= link_to(image_tag("back2.png"), welcome_index_path) %>

app/views/quotes/index.html.erb
<h1>Listing articles</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @quotess.each do |q| %>
    <tr>
      <td><%= q.words %></td>
      <td><%= q.author %></td>
      <td><%= q.user %></td>
    </tr>
  <% end %>
</table>

app/views/quotes/new.html.erb
<%= form_for :quotes, url: quotes_path do |f| %>
  <p style="color:blue;font-size:30px">
    <%= f.label :quote %><br>
    <%= f.text_area :words %>
  </p>
 
  <p style="color:blue;font-size:30px">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </p>
	
	<%= f.hidden_field :user, :value => @currentUser.to_s %>
  <p >
    <%= f.submit %>
  </p>
  <%= link_to(image_tag("back2.png"), welcome_index_path) %>
<% end %>

app/views/quotes/show.html.erb
<h1 style="color:blue;font-size:35px" >Congrats, you just added a new quote</h1>
<p style="color:blue;font-size:30px">
  <strong>Words:</strong>
  "<%= @quote.words %>"
</p>
 
<p style="color:blue;font-size:30px">
  <strong>Author:</strong>
  <%= @quote.author %>
</p>
<%= link_to(image_tag("back2.png"), welcome_index_path) %>

app/views/users/new.html.erb
<h1 style="color:blue">Signup</h1>

<%= form_for :user, url: '/users' do |f| %>

  Username: <%= f.text_field :name %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>

app/views/welcome/index.html.erb
<div>


<h1 style="font-size:40px; color:blue"> Daily Quotes</h1>

<%= link_to(image_tag("sharequote.png"), new_quote_path) %>
<%= link_to(image_tag("add_friend.png"), new_follow_path) %>
<%= link_to(image_tag("quoteimg.png"), new_like_path) %>

</div>
<br>
<div style="color:blue; font-size:20pt">Followers: <%= @followercount %>
Following: <%= @followingcount %></div>
<br>
<br>
<% @quotess.each do |q| %>
	<div id="quote_show">
		<div id="timee"> 
			<%= (q.created_at - (4*60*60)).month %> / <%= (q.created_at - (4*60*60)).day %> <br>
			<%= show_time(q) %>
		</div>
    	 "<%= q.words %>" <br>
   		  - <%= q.author %> <br>
    </div>
  <% end %>